on:
  workflow_call:
    inputs:
      RepoName:
        description: "The name for image."
        required: true
        type: string

env:
  ANSIBLE_USER: 'github'
  ANSIBLE_HOST: '2.58.67.208'
  ANSIBLE_PORT: '2023'
  REPO_NAME: ${{ inputs.RepoName }}
  BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:

    - name: Create Key File
      run: |
        echo "$BOT_PRIVATE_KEY" > ~/keyfile
        sed -i 's/\r//' ~/keyfile
        chmod 600 ~/keyfile

    - name: Git Clone Repo on Remote
      run: >
        ssh -p $ANSIBLE_PORT -o StrictHostKeyChecking=no $ANSIBLE_USER@$ANSIBLE_HOST -i ~/keyfile
        "cd /usr/local/i-advert/devops && git fetch --all && git reset --hard origin/master && git clean -fd"

    - name: Run Ansible Playbook on Remote
      run: >
        ssh -p $ANSIBLE_PORT -o StrictHostKeyChecking=no $ANSIBLE_USER@$ANSIBLE_HOST -i ~/keyfile
        "cd /usr/local/i-advert/devops &&
        ansible-playbook ${REPO_NAME#*/}/playbooks/update.yml -i ${REPO_NAME#*/}/hosts.yaml --private-key /usr/local/i-advert/github_key"
