on:
  workflow_dispatch:
    inputs:
    # Format several paths as a ';' separated string
      Playbooks:
        description: "The name for image."
        required: true
        type: string
      PrivateKey:
        description: "Ansible client's private SSH key"
        required: true
        type: string
      PublicKey:
        description: "Ansible client's public SSH key"
        required: true
        type: string

      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install ansible
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: pipx install --include-deps ansible

      - name: Run Playbooks
        run: |
          for playbook in {{ PathToPlaybook }} 
          sudo ansible-playbook --private-key {{ PrivateKey }} \
          -i {{ PathToInventory }} {{ PathToPlaybook }}

      - name: 
